# Generated by Django 3.0.2 on 2020-02-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
