# Generated by Django 3.0.2 on 2020-02-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200131_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pay_type', models.CharField(max_length=10)),
                ('date_stamp', models.DateField()),
                ('amount', models.FloatField()),
                ('card_name', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.CreditCard')),
                ('category', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.Category')),
            ],
        ),
    ]
