# Generated by Django 3.0.2 on 2020-02-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200131_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='category',
            field=models.OneToOneField(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.Category'),
        ),
    ]
