# Generated by Django 3.0.2 on 2020-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200204_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
