# Generated by Django 3.0.2 on 2020-02-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200205_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='card_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.CreditCard'),
        ),
        migrations.AlterField(
            model_name='expenselineitem',
            name='category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.Category'),
        ),
    ]
