# Generated by Django 3.0.2 on 2020-02-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_creditcard_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLineItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date_stamp', models.DateField()),
                ('from_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_unused_1', to='budget.BankAccount')),
                ('to_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_unused_2', to='budget.BankAccount')),
            ],
        ),
    ]
