# Generated by Django 3.0.2 on 2020-02-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_creditcardpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpayment',
            name='from_bank',
            field=models.ForeignKey(default='_defunct_acct', on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.BankAccount'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='to_credit_card',
            field=models.ForeignKey(default='_defunct_cc', on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.CreditCard'),
        ),
    ]
