# Generated by Django 3.0.2 on 2020-02-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20200208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
