# Generated by Django 3.0.2 on 2020-02-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_auto_20200209_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.BankAccount'),
        ),
    ]
