# Generated by Django 3.0.2 on 2020-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20200212_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
