# Generated by Django 3.0.2 on 2020-02-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_auto_20200214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
