# Generated by Django 3.0.4 on 2020-03-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_auto_20200218_1743'),
        ('budget', '0028_auto_20200218_1746'),
    ]

    operations = [
    ]
