# Generated by Django 3.0.2 on 2020-01-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('date_stamp', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
