# Generated by Django 3.0.2 on 2020-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200205_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
