# Generated by Django 3.0.2 on 2020-02-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_bankaccount_revcategory_revenuelineitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpCategory',
        ),
    ]
