# Generated by Django 3.0.2 on 2020-02-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20200205_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='nickname',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
