# Generated by Django 3.0.2 on 2020-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20200205_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='colour',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
