# Generated by Django 3.0.2 on 2020-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_banklineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='pay_type',
            field=models.CharField(choices=[('cash', 'cash'), ('debit', 'debit'), ('credit', 'credit')], max_length=6),
        ),
        migrations.AlterField(
            model_name='revenuelineitem',
            name='cash_debit',
            field=models.CharField(choices=[('cash', 'cash'), ('debit', 'debit')], max_length=5),
        ),
    ]
