# Generated by Django 3.0.2 on 2020-02-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20200208_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date_stamp', models.DateField()),
                ('from_bank', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.BankAccount')),
                ('to_credit_card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.CreditCard')),
            ],
        ),
    ]
