# Generated by Django 3.0.2 on 2020-02-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_bankaccount_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='name',
            new_name='nickname',
        ),
    ]
