# Generated by Django 3.0.2 on 2020-02-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_expenselineitem_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardLineItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date_stamp', models.DateField()),
                ('to_credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.CreditCard')),
            ],
        ),
    ]
